image: node:14.5.0
cache:
  paths:
    - node_modules/
pages:
    stage: deploy
    only:
    - master
    script:
    - npm install
    - npx webpack
    tags:
      - shared-fi
    artifacts:
        paths:
          - public
